apiVersion: v1
kind: ServiceAccount
metadata:
  name: syncer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syncer-cr
rules:
- apiGroups: [""]
  resources: ["configmaps"] # Object 지정
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: syncer-crb
subjects:
- kind: ServiceAccount
  name: syncer-sa
  namespace: default
roleRef:
  kind: ClusterRole 
  name: syncer-cr
  apiGroup: rbac.authorization.k8s.io
