apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: syncer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: syncer 
    spec:
      containers:
        - name: syncer 
          image: mrchypark/syncer
          resources:
            requests:
              memory: "8Mi"
              cpu: "100m"
            limits:
              memory: "8Mi"
              cpu: "100m"