name: Publish Docker
on: [push, release]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Build, Tag, Push
        uses: mattdavis0351/actions/docker-gpr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: syncer
          dockerfile-location: .
